name: iron_log
description: "IronLog — A personal record tracker for the gym."
publish_to: 'none'
version: 1.0.0+1

environment:
  sdk: ^3.9.2

dependencies:
  flutter:
    sdk: flutter
  shared_preferences: ^2.2.3
  fl_chart: ^1.1.1
  azlistview: ^2.0.0
  sticky_az_list: ^0.0.7
  crypto: ^3.0.3
  http: ^1.1.0
  cupertino_icons: ^1.0.8

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^6.0.0
  flutter_launcher_icons: ^0.14.4

flutter:
  uses-material-design: true
  assets:
    - assets/images/ironlog_logo.png

flutter_launcher_icons:
  image_path: assets/images/ironlog_logo.png

  android: true
  ios: true

  web:
    generate: true
    image_path: assets/images/ironlog_logo.png
    background_color: "#3B3541"
    theme_color: "#3B3541"

  macos:
    generate: true
    image_path: assets/images/ironlog_logo.png

  windows:
    generate: true
    image_path: assets/images/ironlog_logo.png
    icon_size: 256
